<a href="https://colab.research.google.com/github/h3it-dias/NLP_Group_Gradientes_Backpropagation/blob/main/pytorch_redes/tensores/Tensores_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensores

## O que é um tensor?

Um tensor é um objeto que se transforma de um jeito específico quando você muda o sistema de coordenadas.

Uma grandeza física existe independente de como você a descreve. A velocidade de um carro é a mesma esteja você medindo com eixos alinhados à rua ou girados 30°. Mas os números que você escreve mudam. Um tensor é o objeto cujos números mudam segundo uma regra precisa, de forma que a grandeza representada continue a mesma.

Nesse sentido, tensores têm ordem:

1.   ordem 0 — escalar (temperatura num ponto)
2.   ordem 1 — vetor (velocidade)
3.   ordem 2 — matriz (tensor de tensão num material)
4.   ordem 3+ — e assim por diante




O que faz algo ser tensor não é ter índices. É a regra de transformação. Uma tabela de preços com dois índices (produto × loja) tem forma de matriz, mas não é um tensor nesse sentido, porque não existe "mudança de coordenadas" que faça sentido ali

## O que é um Tensor para o Pytorch

Um tensor é um array multidimensional de números, com um tipo, um device e um shape.

In [1]:
import torch
import numpy as np

## Inicializando um Tensor

Podem ser criados diretamente dos dados.

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

###  Apartir de um array NumPy

Tensores no podem ser criados apartir de numPy arrays, o mesmo vale para o contrário

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

### Apartir de outro Tensor

O novo tensor preserva as propriedades (forma, tipo de dado) do tensor de argumento, a menos que sejam explicitamente substituídas.

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1359, 0.7295],
        [0.7057, 0.4599]]) 



### Com valores aleatórios ou constantes

`shape` é uma tupla de dimensões do tensor, determinando a dimensionalidade do tensor de saída.

In [13]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9467, 0.7075, 0.8010],
        [0.6568, 0.3956, 0.1057]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Atributos de um Tensor

In [15]:
tensor = torch.rand(3,4)

print(f"Forma do tensor: {tensor.shape}")
print(f"Tipo de dado do tensor: {tensor.dtype}")
print(f"Dispositivo no qual o tensor está armazenado: {tensor.device}")

Forma do tensor: torch.Size([3, 4])
Tipo de dado do tensor: torch.float32
Dispositivo no qual o tensor está armazenado: cpu


## Operações com tensores

Por padrão, um tensor é criado na CPU, mas pode ser movido para um acelerador, porém isso deve ser feito de forma explicita com o metodo `.to`.

In [19]:
# Transferimos nosso tensor para o acelerador atual, se disponível.
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

### Indexação e fatiamento padrão estilo NumPy

Operações de fatiamento em arrays, por meio do indice.

In [20]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Operações aritméticas

In [23]:
# Isso calcula a multiplicação de matrizes entre dois tensores. y1, y2 e y3 terão o mesmo valor
# ``tensor.T`` retorna a transposta de um tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# Isso calcula o produto elemento a elemento. z1, z2 e z3 terão o mesmo valor.
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])